name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-latest
    strategy: 
      matrix:
        run-config:
          - { scheme: 'RSCore', destination: 'platform=macOS'}
          - { scheme: 'RSCoreiOS', destination: 'platform=iOS Simulator,OS=13.0,name=iPhone 11' }

    steps:
    - name: Checkout Project
      uses: actions/checkout@v1

    - name: Switch to Xcode 11
      run: sudo xcode-select -s /Applications/Xcode_11.app

    - name: Build Version
      run: xcodebuild -version

    - name: Build Settings
      run: xcodebuild -showBuildSettings
      
    - name: Build SDK
      run: xcodebuild -showsdks
    
    - name: Show Available Destinations
      run: xcodebuild -scheme RSCoreiOS -showdestinations

    - name: Run Build
      env:
        scheme: ${{ matrix.run-config['scheme'] }}
        destination: ${{ matrix.run-config['destination'] }}
      run: xcodebuild -scheme ${scheme} test -destination "${destination}" -showBuildTimingSummary CODE_SIGN_IDENTITY=
